name: Build and Deploy WAR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build WAR
        run: jar cvf helloworld.war -C .
          
