name: Build and Deploy WAR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build WAR
        run: |
          ./gradlew war

      - name: Display WAR file
        run: ls build/libs/*.war
