name: Build and Deploy WAR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.3.3-bin.zip
          unzip -d $HOME gradle-7.3.3-bin.zip
          echo "export PATH=$HOME/gradle-7.3.3/bin:$PATH" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Build WAR
        run: |
          gradle wrapper
          ./gradlew war
