name: Build and Deploy WAR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
          
      - name: Build WAR
        run: jar cvf helloworld.war WEB-INF
          
      - name: Display WAR file
        run: ls helloworld.war

      - name: Deploy WAR
        run: |
          mkdir -p deployment
          cp helloworld.war deployment/

      - name: Store WAR file in repo
        run: |
          mkdir -p war
          cp helloworld.war war/
          git add war
          git commit -m "Add WAR file"
          git push origin master
          
